-- =====================================================
-- Migration: Create Topic Groups System
-- Description: Sistema para agrupar topics en exámenes secuenciales
-- Date: 2025-10-31
-- =====================================================

-- =====================================================
-- 1. Crear tabla topic_groups
-- =====================================================

CREATE TABLE IF NOT EXISTS "public"."topic_groups" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "academy_id" BIGINT NOT NULL REFERENCES "public"."academies"("id") ON DELETE RESTRICT,

  -- Configuración común (sincronizada con topics del grupo)
  "enabled" BOOLEAN DEFAULT true NOT NULL,
  "is_premium" BOOLEAN DEFAULT false NOT NULL,
  "published_at" TIMESTAMPTZ,
  "image_url" TEXT,
  "duration_seconds" BIGINT,

  -- Auditoría
  "created_at" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT "topic_groups_name_check" CHECK (length(trim("name")) > 0)
);

ALTER TABLE "public"."topic_groups" OWNER TO "postgres";

COMMENT ON TABLE "public"."topic_groups" IS
'Agrupa topics para crear exámenes secuenciales (ej: Conocimientos → Psicos → Ortografía)';

COMMENT ON COLUMN "public"."topic_groups"."enabled" IS
'Si está deshabilitado, el grupo no aparece en la app';

COMMENT ON COLUMN "public"."topic_groups"."is_premium" IS
'Si es premium, solo usuarios premium pueden acceder';

COMMENT ON COLUMN "public"."topic_groups"."published_at" IS
'Fecha de publicación del grupo. Si es NULL, no está publicado';

-- Índices
CREATE INDEX "idx_topic_groups_academy" ON "public"."topic_groups"("academy_id") WHERE "enabled" = true;
CREATE INDEX "idx_topic_groups_published" ON "public"."topic_groups"("published_at") WHERE "published_at" IS NOT NULL;

-- =====================================================
-- 2. Modificar tabla topic (añadir relación con topic_groups)
-- =====================================================

ALTER TABLE "public"."topic"
ADD COLUMN IF NOT EXISTS "topic_group_id" BIGINT REFERENCES "public"."topic_groups"("id") ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS "group_order" INTEGER;

COMMENT ON COLUMN "public"."topic"."topic_group_id" IS
'Si pertenece a un grupo, referencia al topic_group. NULL si el topic va solo';

COMMENT ON COLUMN "public"."topic"."group_order" IS
'Orden de aparición dentro del grupo (1, 2, 3...). NULL si no pertenece a ningún grupo';

-- Constraint: si topic_group_id no es null, group_order debe ser mayor que 0
ALTER TABLE "public"."topic"
ADD CONSTRAINT "check_group_order"
CHECK (
  ("topic_group_id" IS NULL AND "group_order" IS NULL)
  OR
  ("topic_group_id" IS NOT NULL AND "group_order" > 0)
);

-- Índice para recuperar topics de un grupo en orden
CREATE INDEX "idx_topic_group_order" ON "public"."topic"("topic_group_id", "group_order")
WHERE "topic_group_id" IS NOT NULL;

-- Constraint único: no puede haber dos topics con el mismo orden en el mismo grupo
CREATE UNIQUE INDEX "idx_topic_group_unique_order"
ON "public"."topic"("topic_group_id", "group_order")
WHERE "topic_group_id" IS NOT NULL;

-- =====================================================
-- 3. Modificar tabla user_tests (para agrupar resultados)
-- =====================================================

ALTER TABLE "public"."user_tests"
ADD COLUMN IF NOT EXISTS "topic_group_id" BIGINT REFERENCES "public"."topic_groups"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."user_tests"."topic_group_id" IS
'Referencia al topic_group cuando este test forma parte de un examen secuencial. Permite agrupar múltiples user_tests que pertenecen a la misma sesión de examen.';

-- Índice para recuperar todos los tests de un grupo
CREATE INDEX "idx_user_tests_topic_group" ON "public"."user_tests"("topic_group_id", "user_id")
WHERE "topic_group_id" IS NOT NULL;

-- =====================================================
-- 4. Trigger para sincronizar datos comunes del grupo a los topics
-- =====================================================

CREATE OR REPLACE FUNCTION "public"."sync_topic_group_to_topics"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Cuando se actualiza un topic_group, sincronizar enabled, is_premium y published_at
  -- a todos los topics que pertenecen a ese grupo

  UPDATE "public"."topic"
  SET
    "enabled" = NEW.enabled,
    "is_premium" = NEW.is_premium,
    "published_at" = NEW.published_at,
    "updated_at" = now()
  WHERE "topic_group_id" = NEW.id;

  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."sync_topic_group_to_topics"() OWNER TO "postgres";

COMMENT ON FUNCTION "public"."sync_topic_group_to_topics"() IS
'Sincroniza enabled, is_premium y published_at del topic_group a todos sus topics';

-- Crear trigger en INSERT y UPDATE
CREATE TRIGGER "trg_sync_topic_group_to_topics"
AFTER INSERT OR UPDATE OF "enabled", "is_premium", "published_at"
ON "public"."topic_groups"
FOR EACH ROW
EXECUTE FUNCTION "public"."sync_topic_group_to_topics"();

-- =====================================================
-- 5. Función y Trigger para actualizar updated_at en topic_groups
-- =====================================================

-- Crear función si no existe para actualizar updated_at
CREATE OR REPLACE FUNCTION "public"."update_topic_groups_updated_at"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."update_topic_groups_updated_at"() OWNER TO "postgres";

-- Crear trigger
CREATE TRIGGER "trigger_update_topic_groups_updated_at"
BEFORE UPDATE ON "public"."topic_groups"
FOR EACH ROW
EXECUTE FUNCTION "public"."update_topic_groups_updated_at"();

-- =====================================================
-- 6. Permisos RLS (Row Level Security)
-- =====================================================

-- Habilitar RLS en topic_groups
ALTER TABLE "public"."topic_groups" ENABLE ROW LEVEL SECURITY;

-- Política: usuarios autenticados pueden leer topic_groups habilitados de su academia
CREATE POLICY "topic_groups_select_policy"
ON "public"."topic_groups"
FOR SELECT
TO authenticated
USING (
  "enabled" = true
  AND "published_at" IS NOT NULL
  AND "published_at" <= now()
);

-- Política: usuarios anónimos pueden leer topic_groups públicos (para preview)
CREATE POLICY "topic_groups_select_anon_policy"
ON "public"."topic_groups"
FOR SELECT
TO anon
USING (
  "enabled" = true
  AND "is_premium" = false
  AND "published_at" IS NOT NULL
  AND "published_at" <= now()
);

-- Política: service_role puede hacer todo
CREATE POLICY "topic_groups_all_service_role"
ON "public"."topic_groups"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- =====================================================
-- 7. Grants de permisos
-- =====================================================

GRANT SELECT ON TABLE "public"."topic_groups" TO anon;
GRANT SELECT ON TABLE "public"."topic_groups" TO authenticated;
GRANT ALL ON TABLE "public"."topic_groups" TO service_role;

GRANT USAGE ON SEQUENCE "public"."topic_groups_id_seq" TO anon;
GRANT USAGE ON SEQUENCE "public"."topic_groups_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."topic_groups_id_seq" TO service_role;

GRANT EXECUTE ON FUNCTION "public"."sync_topic_group_to_topics"() TO service_role;
