-- =====================================================
-- OPN Index System - Tables and Views
-- =====================================================
-- Description: Creates the OPN Index ranking system that measures user progress
--              through quality trends, recent activity, competitiveness and momentum
-- Author: OPN System
-- Date: 2025-11-05
-- =====================================================

-- =====================================================
-- 1. Create user_opn_index_history table
-- =====================================================
-- Stores complete history of OPN Index calculations
-- Allows temporal analysis and progress tracking

CREATE TABLE IF NOT EXISTS "public"."user_opn_index_history" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,

  -- Total index (0-1000)
  "opn_index" INTEGER NOT NULL,

  -- Breakdown by component
  "quality_trend_score" NUMERIC(6,2) DEFAULT 0,     -- Max: 400
  "recent_activity_score" NUMERIC(6,2) DEFAULT 0,   -- Max: 300
  "competitive_score" NUMERIC(6,2) DEFAULT 0,       -- Max: 200
  "momentum_score" NUMERIC(6,2) DEFAULT 0,          -- Max: 100

  -- Global rank (calculated after all users)
  "global_rank" INTEGER,

  -- Calculation timestamp
  "calculated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Audit
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================
-- 2. Create indexes for performance
-- =====================================================

-- Index for user history queries (most common)
CREATE INDEX IF NOT EXISTS "idx_opn_history_user_date"
  ON "public"."user_opn_index_history"("user_id", "calculated_at" DESC);

-- Index for ranking queries
CREATE INDEX IF NOT EXISTS "idx_opn_history_index"
  ON "public"."user_opn_index_history"("opn_index" DESC);

-- Index for time-based queries
CREATE INDEX IF NOT EXISTS "idx_opn_history_calculated"
  ON "public"."user_opn_index_history"("calculated_at" DESC);

-- Composite index for global ranking queries
CREATE INDEX IF NOT EXISTS "idx_opn_history_rank_date"
  ON "public"."user_opn_index_history"("calculated_at" DESC, "opn_index" DESC);

-- =====================================================
-- 3. Create view for current OPN Index
-- =====================================================
-- Shows the latest value for each user (for global ranking)

CREATE OR REPLACE VIEW "public"."user_opn_index_current" AS
SELECT DISTINCT ON (user_id)
  user_id,
  opn_index,
  quality_trend_score,
  recent_activity_score,
  competitive_score,
  momentum_score,
  global_rank,
  calculated_at
FROM "public"."user_opn_index_history"
ORDER BY user_id, calculated_at DESC;

-- =====================================================
-- 4. Create RLS policies
-- =====================================================

-- Enable RLS
ALTER TABLE "public"."user_opn_index_history" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view all OPN index data (public rankings)
CREATE POLICY "opn_index_select_all" ON "public"."user_opn_index_history"
  FOR SELECT
  USING (true);

-- Policy: Only service role can insert OPN index data
CREATE POLICY "opn_index_insert_service" ON "public"."user_opn_index_history"
  FOR INSERT
  WITH CHECK (false);  -- Only service role (via edge function) can insert

-- Policy: No updates allowed (immutable history)
CREATE POLICY "opn_index_no_updates" ON "public"."user_opn_index_history"
  FOR UPDATE
  USING (false);

-- Policy: No deletes allowed (preserve history)
CREATE POLICY "opn_index_no_deletes" ON "public"."user_opn_index_history"
  FOR DELETE
  USING (false);

-- =====================================================
-- 5. Add helpful comments
-- =====================================================

COMMENT ON TABLE "public"."user_opn_index_history" IS
'Stores historical OPN Index calculations for all users. Updated daily via Edge Function.';

COMMENT ON COLUMN "public"."user_opn_index_history"."opn_index" IS
'Total OPN Index score (0-1000 points)';

COMMENT ON COLUMN "public"."user_opn_index_history"."quality_trend_score" IS
'Quality Trend component (0-400 pts): Measures improvement in accuracy over time';

COMMENT ON COLUMN "public"."user_opn_index_history"."recent_activity_score" IS
'Recent Activity component (0-300 pts): Measures practice volume in last 30 days';

COMMENT ON COLUMN "public"."user_opn_index_history"."competitive_score" IS
'Competitiveness component (0-200 pts): Measures positions in Mock rankings';

COMMENT ON COLUMN "public"."user_opn_index_history"."momentum_score" IS
'Momentum component (0-100 pts): Measures acceleration and recent improvement';

COMMENT ON COLUMN "public"."user_opn_index_history"."global_rank" IS
'Global ranking position among all users (1 = best)';

COMMENT ON VIEW "public"."user_opn_index_current" IS
'View showing the most recent OPN Index for each user (used for global ranking)';