-- =====================================================
-- MIGRATION 1: TABLES AND ENUMS
-- =====================================================
-- Descripción: Tablas y enumeradores base del sistema
-- Fecha: 2025-11-05
-- =====================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- =====================================================
-- EXTENSIONS
-- =====================================================

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

-- =====================================================
-- ENUMS
-- =====================================================

-- Enum para estados de impugnaciones
CREATE TYPE "public"."challenge_state" AS ENUM (
    'pendiente',
    'resuelta',
    'rechazada'
);

ALTER TYPE "public"."challenge_state" OWNER TO "postgres";

-- Enum para niveles de topics
CREATE TYPE "public"."topic_level" AS ENUM (
    'Mock',
    'Study',
    'Flashcard'
);

ALTER TYPE "public"."topic_level" OWNER TO "postgres";

COMMENT ON TYPE "public"."topic_level" IS 'Tipos de topics: Mock (simulacros), Study (estudio), Flashcard (tarjetas de estudio con spaced repetition)';

-- =====================================================
-- TABLES
-- =====================================================

-- -----------------------------------------------------
-- 1. ACADEMIES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."academies" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "slug" character varying NOT NULL,
    "description" "text",
    "logo_url" character varying,
    "website" character varying,
    "contact_email" character varying,
    "contact_phone" character varying,
    "address" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."academies" OWNER TO "postgres";

ALTER TABLE "public"."academies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."academies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 2. SPECIALTIES (Especialidades por academia)
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."specialties" (
    "id" bigint NOT NULL,
    "academy_id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "slug" character varying(100) NOT NULL,
    "description" "text",
    "icon_url" "text",
    "color_hex" character varying(7),
    "is_default" boolean DEFAULT false NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "display_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."specialties" OWNER TO "postgres";

ALTER TABLE "public"."specialties" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."specialties_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 3. ACADEMY KPIs
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."academy_kpis" (
    "id" bigint NOT NULL,
    "academy_id" bigint NOT NULL,
    "total_questions" bigint DEFAULT 0 NOT NULL,
    "total_topics" bigint DEFAULT 0 NOT NULL,
    "total_users" bigint DEFAULT 0 NOT NULL,
    "total_tests" bigint DEFAULT 0 NOT NULL,
    "total_premium_users" bigint DEFAULT 0 NOT NULL,
    "premium_plus_users" bigint DEFAULT 0 NOT NULL,
    "total_users_today" bigint DEFAULT 0 NOT NULL,
    "new_users_today" bigint DEFAULT 0 NOT NULL,
    "total_answers_today" bigint DEFAULT 0 NOT NULL,
    "total_flashcard_answers_today" bigint DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."academy_kpis" OWNER TO "postgres";

ALTER TABLE "public"."academy_kpis" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."academy_kpis_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 4. ROLES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."role" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."role" OWNER TO "postgres";

ALTER TABLE "public"."role" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 5. CMS USERS (Usuarios administrativos)
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."cms_users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_uuid" "uuid" DEFAULT "gen_random_uuid"(),
    "academy_id" bigint DEFAULT 1 NOT NULL,
    "username" "text" DEFAULT 'sin usuario'::"text",
    "nombre" "text" DEFAULT 'sin nombre'::"text",
    "apellido" "text" DEFAULT 'sin apellido'::"text",
    "avatar_url" "text",
    "email" "text",
    "phone" "text",
    "address" "text",
    "role_id" bigint DEFAULT 4 NOT NULL,
    "specialty_id" bigint,
    CONSTRAINT "cms_users_email_check" CHECK ((("email" IS NULL) OR ("email" ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::"text"))),
    CONSTRAINT "cms_users_username_check" CHECK (("length"(TRIM(BOTH FROM "username")) > 0))
);

ALTER TABLE "public"."cms_users" OWNER TO "postgres";

COMMENT ON COLUMN "public"."cms_users"."academy_id" IS 'Academia a la que pertenece el usuario editor/tutor';

ALTER TABLE "public"."cms_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cms_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 6. USERS (Usuarios de la app)
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "username" character varying NOT NULL,
    "email" "text",
    "first_name" "text",
    "last_name" "text",
    "phone" "text",
    "totalQuestions" bigint DEFAULT 0 NOT NULL,
    "rightQuestions" bigint DEFAULT 0 NOT NULL,
    "wrongQuestions" bigint DEFAULT 0 NOT NULL,
    "tester" boolean DEFAULT false,
    "lastUsed" timestamp with time zone,
    "fcm_token" "text",
    "fid_token" "text",
    "profile_image" "text",
    "unlocked_at" timestamp with time zone,
    "unlock_duration_minutes" integer DEFAULT 0,
    "enabled" boolean DEFAULT true,
    "tutorial" boolean DEFAULT false,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "wordpress_user_id" bigint,
    "display_name" "text",
    "academy_id" bigint DEFAULT 1 NOT NULL,
    "specialty_id" bigint,
    "question_goal" integer DEFAULT 50,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamp with time zone
);

ALTER TABLE "public"."users" OWNER TO "postgres";

COMMENT ON COLUMN "public"."users"."wordpress_user_id" IS 'ID del usuario en WordPress. Usado para sincronización con WP.';
COMMENT ON COLUMN "public"."users"."display_name" IS 'Nombre completo para mostrar del usuario (de WordPress).';
COMMENT ON COLUMN "public"."users"."academy_id" IS 'Academia a la que pertenece el usuario final de la app';
COMMENT ON COLUMN "public"."users"."question_goal" IS 'Daily question goal for the user (default: 50)';
COMMENT ON COLUMN "public"."users"."deleted" IS 'Marca si el usuario ha sido eliminado (soft delete)';
COMMENT ON COLUMN "public"."users"."deleted_at" IS 'Fecha y hora en que el usuario fue eliminado';

ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 7. MEMBERSHIP LEVELS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."membership_levels" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "description" "text",
    "wordpress_rcp_id" integer,
    "wordpress_level_name" character varying(100),
    "revenuecat_product_ids" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "revenuecat_entitlement_id" character varying(100),
    "duration_days" integer,
    "is_recurring" boolean DEFAULT false,
    "trial_days" integer DEFAULT 0,
    "max_content_access" integer,
    "features" "jsonb",
    "price_usd" numeric(10,2),
    "price_eur" numeric(10,2),
    "currency_code" character varying(3) DEFAULT 'EUR'::character varying,
    "is_active" boolean DEFAULT true,
    "display_order" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "specialty_id" bigint NOT NULL,
    "access_level" integer DEFAULT 1 NOT NULL,
    CONSTRAINT "membership_levels_access_level_positive" CHECK (("access_level" > 0)),
    CONSTRAINT "membership_levels_name_check" CHECK (("length"(TRIM(BOTH FROM "name")) > 0))
);

ALTER TABLE "public"."membership_levels" OWNER TO "postgres";

COMMENT ON COLUMN "public"."membership_levels"."specialty_id" IS 'Especialidad a la que pertenece este nivel de membresía.';
COMMENT ON COLUMN "public"."membership_levels"."access_level" IS 'Nivel de acceso desde WordPress RCP. Puede ser cualquier número positivo según la configuración de RCP.';

ALTER TABLE "public"."membership_levels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."membership_levels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 8. USER MEMBERSHIPS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."user_memberships" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "membership_level_id" bigint NOT NULL,
    "status" character varying(50) DEFAULT 'active'::character varying,
    "started_at" timestamp with time zone DEFAULT "now"(),
    "expires_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "auto_renews" boolean DEFAULT false,
    "renewal_grace_period_days" integer DEFAULT 3,
    "last_synced_at" timestamp with time zone DEFAULT "now"(),
    "sync_source" character varying(50),
    "sync_status" character varying(50) DEFAULT 'synced'::character varying,
    "sync_error" "text",
    "metadata" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "user_memberships_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'cancelled'::character varying, 'expired'::character varying, 'pending'::character varying])::"text"[]))),
    CONSTRAINT "user_memberships_sync_source_check" CHECK ((("sync_source")::"text" = ANY ((ARRAY['revenuecat'::character varying, 'wordpress'::character varying, 'manual'::character varying, 'auto_freemium'::character varying])::"text"[]))),
    CONSTRAINT "user_memberships_sync_status_check" CHECK ((("sync_status")::"text" = ANY ((ARRAY['synced'::character varying, 'pending'::character varying, 'error'::character varying])::"text"[])))
);

ALTER TABLE "public"."user_memberships" OWNER TO "postgres";

ALTER TABLE "public"."user_memberships" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_memberships_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 9. TOPIC TYPES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."topic_type" (
    "id" bigint NOT NULL,
    "topic_type_name" character varying NOT NULL,
    "description" "text",
    "level" "public"."topic_level" DEFAULT 'Study'::"public"."topic_level" NOT NULL,
    "default_number_options" integer DEFAULT 4 NOT NULL,
    "penalty" numeric(4,2) DEFAULT 0.5 NOT NULL,
    "time_by_question" numeric(4,2) DEFAULT 1.0 NOT NULL,
    "order_of_appearance" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."topic_type" OWNER TO "postgres";

ALTER TABLE "public"."topic_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."topic_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 10. CATEGORIES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "topic_type" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."categories" OWNER TO "postgres";

ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 11. TOPIC GROUPS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."topic_groups" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "description" "text",
    "academy_id" bigint NOT NULL,
    "topic_type_id" bigint NOT NULL,
    "enabled" boolean DEFAULT true NOT NULL,
    "is_premium" boolean DEFAULT false NOT NULL,
    "published_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."topic_groups" OWNER TO "postgres";

COMMENT ON TABLE "public"."topic_groups" IS 'Grupos de topics que se pueden hacer en secuencia (ej: Simulacro completo con múltiples temas)';

ALTER TABLE "public"."topic_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."topic_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 12. TOPICS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."topic" (
    "id" bigint NOT NULL,
    "topic_type_id" bigint NOT NULL,
    "topic_name" "text" NOT NULL,
    "description" "text",
    "enabled" boolean DEFAULT true NOT NULL,
    "is_premium" boolean DEFAULT false NOT NULL,
    "is_hidden_but_premium" boolean DEFAULT false NOT NULL,
    "published_at" timestamp with time zone,
    "total_participants" bigint DEFAULT 0 NOT NULL,
    "total_questions" bigint DEFAULT 0 NOT NULL,
    "total_score" bigint DEFAULT 0 NOT NULL,
    "average_score" numeric(5,2) GENERATED ALWAYS AS (
        CASE
            WHEN ("total_participants" > 0) THEN "round"((("total_score")::numeric / ("total_participants")::numeric), 2)
            ELSE NULL::numeric
        END
    ) STORED,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "options" integer DEFAULT 3 NOT NULL,
    "max_score" integer DEFAULT 0,
    "min_score" integer DEFAULT 0,
    "academy_id" bigint DEFAULT 1 NOT NULL,
    "duration_seconds" bigint DEFAULT '0'::bigint,
    "image_url" "text",
    "order" integer,
    "category_id" bigint,
    "specialty_id" bigint,
    "topic_group_id" bigint,
    "group_order" integer,
    CONSTRAINT "topic_name_check" CHECK (("length"("topic_name") > 0))
);

ALTER TABLE "public"."topic" OWNER TO "postgres";

COMMENT ON COLUMN "public"."topic"."options" IS 'Number of options by default in questions';
COMMENT ON COLUMN "public"."topic"."order" IS 'Orden de aparición del topic dentro de su tipo';
COMMENT ON COLUMN "public"."topic"."category_id" IS 'Categoría del topic (ej: Derecho, Sociología, Técnico)';
COMMENT ON COLUMN "public"."topic"."topic_group_id" IS 'ID del grupo al que pertenece este topic (NULL si va solo)';
COMMENT ON COLUMN "public"."topic"."group_order" IS 'Orden dentro del grupo (para exámenes secuenciales)';

ALTER TABLE "public"."topic" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."topic_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 13. QUESTIONS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "question" "text" NOT NULL,
    "tip" "text",
    "topic" bigint NOT NULL,
    "article" "text",
    "question_image_url" "text" DEFAULT '' NOT NULL,
    "retro_image_url" "text" DEFAULT '' NOT NULL,
    "retro_audio_enable" boolean DEFAULT false NOT NULL,
    "retro_audio_text" "text" DEFAULT '' NOT NULL,
    "retro_audio_url" "text" DEFAULT '' NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    "published" boolean DEFAULT true NOT NULL,
    "shuffled" boolean,
    "num_answered" integer DEFAULT 0 NOT NULL,
    "num_fails" integer DEFAULT 0 NOT NULL,
    "num_empty" integer DEFAULT 0 NOT NULL,
    "difficult_rate" double precision GENERATED ALWAYS AS (
        CASE
            WHEN ("num_answered" + "num_fails" + "num_empty") > 0
            THEN "round"((("num_fails" + "num_empty")::numeric / ("num_answered" + "num_fails" + "num_empty")::numeric), 3)
            ELSE 0.0
        END
    ) STORED,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" "uuid",
    "challenge_by_tutor" boolean DEFAULT false NOT NULL,
    "challenge_reason" "text",
    "academy_id" bigint DEFAULT 1 NOT NULL
);

ALTER TABLE "public"."questions" OWNER TO "postgres";

-- -----------------------------------------------------
-- 14. QUESTION OPTIONS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."question_options" (
    "id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "answer" "text" NOT NULL,
    "is_correct" boolean DEFAULT false NOT NULL,
    "option_order" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."question_options" OWNER TO "postgres";

ALTER TABLE "public"."question_options" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_options_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 15. REMOVED QUESTIONS HISTORY
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."removed_questions_history" (
    "id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "question_text" "text" NOT NULL,
    "topic_id" bigint NOT NULL,
    "removed_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "removed_by" "uuid",
    "reason" "text"
);

ALTER TABLE "public"."removed_questions_history" OWNER TO "postgres";

ALTER TABLE "public"."removed_questions_history" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."removed_questions_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 16. USER TESTS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."user_tests" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "topic_ids" bigint[] NOT NULL,
    "options" smallint DEFAULT 4 NOT NULL,
    "right_questions" integer DEFAULT 0 NOT NULL,
    "wrong_questions" integer DEFAULT 0 NOT NULL,
    "question_count" integer DEFAULT 0 NOT NULL,
    "total_answered" integer DEFAULT 0 NOT NULL,
    "score" real,
    "finalized" boolean DEFAULT false NOT NULL,
    "visible" boolean DEFAULT true NOT NULL,
    "study_mode" boolean DEFAULT false NOT NULL,
    "study_failed" boolean DEFAULT false NOT NULL,
    "study_white" boolean DEFAULT false NOT NULL,
    "mock" boolean,
    "survival" boolean DEFAULT false,
    "mark_collection" boolean,
    "minutes" integer,
    "time_spent_millis" integer,
    "special_topic" bigint,
    "special_topic_title" "text",
    "difficulty_end" real,
    "number_of_lives" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_flashcard_mode" boolean DEFAULT false,
    "duration_seconds" integer,
    "topic_group_id" bigint
);

ALTER TABLE "public"."user_tests" OWNER TO "postgres";

COMMENT ON COLUMN "public"."user_tests"."is_flashcard_mode" IS 'Indica si el test es una sesión de estudio con flashcards (no se cuentan right/wrong questions)';
COMMENT ON COLUMN "public"."user_tests"."duration_seconds" IS 'Duration in seconds that the user took to complete the test (nueva columna, preferir sobre minutes)';
COMMENT ON COLUMN "public"."user_tests"."topic_group_id" IS 'ID del grupo de examen al que pertenece este test. Permite agrupar múltiples user_tests que forman parte del mismo examen secuencial.';

ALTER TABLE "public"."user_tests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_tests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 17. USER TEST ANSWERS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."user_test_answers" (
    "id" bigint NOT NULL,
    "user_test_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "selected_option_id" bigint,
    "correct" boolean,
    "time_taken_seconds" integer,
    "question_order" integer NOT NULL,
    "challenge_by_tutor" boolean DEFAULT false NOT NULL,
    "answered_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "difficulty_rating" character varying(10),
    "next_review_date" timestamp with time zone,
    "review_interval_days" integer DEFAULT 1,
    "ease_factor" numeric(4,2) DEFAULT 2.50,
    "repetitions" integer DEFAULT 0,
    "time" bigint,
    CONSTRAINT "user_test_answers_difficulty_rating_check" CHECK ((("difficulty_rating" IS NULL) OR (("difficulty_rating")::"text" = ANY ((ARRAY['again'::character varying, 'hard'::character varying, 'medium'::character varying, 'easy'::character varying])::"text"[]))))
);

ALTER TABLE "public"."user_test_answers" OWNER TO "postgres";

COMMENT ON COLUMN "public"."user_test_answers"."difficulty_rating" IS 'Rating de dificultad para flashcards: again (no la sabía), hard (difícil), medium (media), easy (fácil)';
COMMENT ON COLUMN "public"."user_test_answers"."next_review_date" IS 'Fecha en que la flashcard debe ser revisada nuevamente (spaced repetition)';
COMMENT ON COLUMN "public"."user_test_answers"."review_interval_days" IS 'Intervalo en días hasta la próxima revisión';
COMMENT ON COLUMN "public"."user_test_answers"."ease_factor" IS 'Factor de facilidad (SM-2 algorithm), mayor = intervalo crece más rápido. Rango típico: 1.3-2.5';
COMMENT ON COLUMN "public"."user_test_answers"."repetitions" IS 'Número de veces que se ha revisado correctamente de forma consecutiva';

ALTER TABLE "public"."user_test_answers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_test_answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 18. CHALLENGES (Impugnaciones)
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."challenge" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "topic_id" bigint,
    "reason" "text" NOT NULL,
    "state" "public"."challenge_state" DEFAULT 'pendiente'::"public"."challenge_state" NOT NULL,
    "reply" "text" DEFAULT '' NOT NULL,
    "editor_id" bigint,
    "open" boolean DEFAULT true NOT NULL,
    "tutor_uuid" "uuid",
    "reviewed_at" timestamp with time zone,
    "academy_id" bigint DEFAULT 1 NOT NULL,
    "specialty_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."challenge" OWNER TO "postgres";

ALTER TABLE "public"."challenge" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."challenge_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 19. USER FAVORITE QUESTIONS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."user_favorite_questions" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."user_favorite_questions" OWNER TO "postgres";

ALTER TABLE "public"."user_favorite_questions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_favorite_questions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 20. TOPIC MOCK RANKINGS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."topic_mock_rankings" (
    "id" bigint NOT NULL,
    "topic_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "topic_group_id" bigint,
    "first_score" numeric(5,2) NOT NULL,
    "best_score" numeric(5,2) NOT NULL,
    "attempts" integer DEFAULT 1 NOT NULL,
    "first_attempt_date" timestamp with time zone NOT NULL,
    "last_attempt_date" timestamp with time zone NOT NULL,
    "rank_position" integer,
    "total_participants" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."topic_mock_rankings" OWNER TO "postgres";

COMMENT ON TABLE "public"."topic_mock_rankings" IS 'Rankings de usuarios por topic Mock';
COMMENT ON COLUMN "public"."topic_mock_rankings"."topic_group_id" IS 'ID del grupo al que pertenece este topic (NULL si el topic va solo). Permite filtrar rankings por grupo de examen.';
COMMENT ON COLUMN "public"."topic_mock_rankings"."first_score" IS 'Score del primer intento (usado para el ranking, inmutable después del primer intento)';
COMMENT ON COLUMN "public"."topic_mock_rankings"."best_score" IS 'Mejor score logrado (puede ser mayor que first_score)';
COMMENT ON COLUMN "public"."topic_mock_rankings"."rank_position" IS 'Posición en el ranking (1 = mejor). Se calcula automáticamente';

ALTER TABLE "public"."topic_mock_rankings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."topic_mock_rankings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- -----------------------------------------------------
-- 21. OPN INDEX TABLES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."opn_index" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "value" numeric(10,4) NOT NULL,
    "date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."opn_index" OWNER TO "postgres";

COMMENT ON TABLE "public"."opn_index" IS 'Tabla para almacenar los índices diarios OPN';

ALTER TABLE "public"."opn_index" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."opn_index_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."opn_index_users" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "date" "date" NOT NULL,
    "score" numeric(5,2),
    "total_questions" integer DEFAULT 0 NOT NULL,
    "right_questions" integer DEFAULT 0 NOT NULL,
    "wrong_questions" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."opn_index_users" OWNER TO "postgres";

COMMENT ON TABLE "public"."opn_index_users" IS 'Rendimiento diario de usuarios para el índice OPN';

ALTER TABLE "public"."opn_index_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."opn_index_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."user_opn_index_history" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "opn_index" integer NOT NULL,
    "quality_trend_score" numeric(6,2) DEFAULT 0,
    "recent_activity_score" numeric(6,2) DEFAULT 0,
    "competitive_score" numeric(6,2) DEFAULT 0,
    "momentum_score" numeric(6,2) DEFAULT 0,
    "global_rank" integer,
    "calculated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."user_opn_index_history" OWNER TO "postgres";

COMMENT ON TABLE "public"."user_opn_index_history" IS 'Stores historical OPN Index calculations for all users. Updated daily via Edge Function.';
COMMENT ON COLUMN "public"."user_opn_index_history"."opn_index" IS 'Total OPN Index score (0-1000 points)';
COMMENT ON COLUMN "public"."user_opn_index_history"."quality_trend_score" IS 'Quality Trend component (0-400 pts): Measures improvement in accuracy over time';
COMMENT ON COLUMN "public"."user_opn_index_history"."recent_activity_score" IS 'Recent Activity component (0-300 pts): Measures practice volume in last 30 days';
COMMENT ON COLUMN "public"."user_opn_index_history"."competitive_score" IS 'Competitiveness component (0-200 pts): Measures positions in Mock rankings';
COMMENT ON COLUMN "public"."user_opn_index_history"."momentum_score" IS 'Momentum component (0-100 pts): Measures acceleration and recent improvement';
COMMENT ON COLUMN "public"."user_opn_index_history"."global_rank" IS 'Global ranking position among all users (1 = best)';

ALTER TABLE "public"."user_opn_index_history" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_opn_index_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- =====================================================
-- PRIMARY KEYS
-- =====================================================

ALTER TABLE ONLY "public"."academies" ADD CONSTRAINT "academies_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."academies" ADD CONSTRAINT "academies_slug_key" UNIQUE ("slug");

ALTER TABLE ONLY "public"."specialties" ADD CONSTRAINT "specialties_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."specialties" ADD CONSTRAINT "specialties_academy_slug_key" UNIQUE ("academy_id", "slug");

ALTER TABLE ONLY "public"."academy_kpis" ADD CONSTRAINT "academy_kpis_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."academy_kpis" ADD CONSTRAINT "academy_kpis_academy_id_key" UNIQUE ("academy_id");

ALTER TABLE ONLY "public"."role" ADD CONSTRAINT "role_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."role" ADD CONSTRAINT "role_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."cms_users" ADD CONSTRAINT "cms_users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."cms_users" ADD CONSTRAINT "cms_users_user_uuid_unique" UNIQUE ("user_uuid");

ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_username_key" UNIQUE ("username");

ALTER TABLE ONLY "public"."membership_levels" ADD CONSTRAINT "membership_levels_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."membership_levels" ADD CONSTRAINT "membership_levels_wordpress_rcp_id_key" UNIQUE ("wordpress_rcp_id");

ALTER TABLE ONLY "public"."user_memberships" ADD CONSTRAINT "user_memberships_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."topic_type" ADD CONSTRAINT "topic_type_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."categories" ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."topic_groups" ADD CONSTRAINT "topic_groups_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."question_options" ADD CONSTRAINT "question_options_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."removed_questions_history" ADD CONSTRAINT "removed_questions_history_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_tests" ADD CONSTRAINT "user_tests_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_test_answers" ADD CONSTRAINT "user_test_answers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_favorite_questions" ADD CONSTRAINT "user_favorite_questions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."user_favorite_questions" ADD CONSTRAINT "user_favorite_questions_user_question_unique" UNIQUE ("user_id", "question_id");

ALTER TABLE ONLY "public"."topic_mock_rankings" ADD CONSTRAINT "topic_mock_rankings_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."topic_mock_rankings" ADD CONSTRAINT "topic_mock_rankings_topic_user_unique" UNIQUE ("topic_id", "user_id");

ALTER TABLE ONLY "public"."opn_index" ADD CONSTRAINT "opn_index_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."opn_index" ADD CONSTRAINT "opn_index_name_date_key" UNIQUE ("name", "date");

ALTER TABLE ONLY "public"."opn_index_users" ADD CONSTRAINT "opn_index_users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."opn_index_users" ADD CONSTRAINT "opn_index_users_user_date_key" UNIQUE ("user_id", "date");

ALTER TABLE ONLY "public"."user_opn_index_history" ADD CONSTRAINT "user_opn_index_history_pkey" PRIMARY KEY ("id");

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX "idx_specialties_academy_active" ON "public"."specialties" USING "btree" ("academy_id", "is_active");
CREATE INDEX "idx_users_academy_id" ON "public"."users" USING "btree" ("academy_id");
CREATE INDEX "idx_users_specialty_id" ON "public"."users" USING "btree" ("specialty_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_membership_levels_wordpress_rcp_id" ON "public"."membership_levels"("wordpress_rcp_id") WHERE "wordpress_rcp_id" IS NOT NULL;
CREATE INDEX "idx_membership_levels_specialty_id" ON "public"."membership_levels" USING "btree" ("specialty_id", "is_active");
CREATE INDEX "idx_topic_academy_type" ON "public"."topic" USING "btree" ("academy_id", "topic_type_id");
CREATE INDEX "idx_topic_category" ON "public"."topic" USING "btree" ("category_id");
CREATE INDEX "idx_topic_specialty_id" ON "public"."topic" USING "btree" ("specialty_id");
CREATE INDEX "idx_topic_group_id" ON "public"."topic" USING "btree" ("topic_group_id");
CREATE INDEX "idx_questions_topic" ON "public"."questions" USING "btree" ("topic");
CREATE INDEX "idx_questions_academy_id" ON "public"."questions" USING "btree" ("academy_id");
CREATE INDEX "idx_question_options_question_id" ON "public"."question_options" USING "btree" ("question_id");
CREATE INDEX "idx_user_tests_user_finalized" ON "public"."user_tests" USING "btree" ("user_id", "finalized");
CREATE INDEX "idx_user_test_answers_user_test" ON "public"."user_test_answers" USING "btree" ("user_test_id");
CREATE INDEX "idx_challenge_specialty_id" ON "public"."challenge" USING "btree" ("specialty_id");
CREATE INDEX "idx_challenge_topic_id" ON "public"."challenge" USING "btree" ("topic_id");
CREATE INDEX "idx_challenge_academy_id" ON "public"."challenge" USING "btree" ("academy_id");
CREATE INDEX "idx_challenge_state_open" ON "public"."challenge" USING "btree" ("state", "open");
CREATE INDEX "idx_rankings_topic_user" ON "public"."topic_mock_rankings" USING "btree" ("topic_id", "user_id");
CREATE INDEX "idx_rankings_user" ON "public"."topic_mock_rankings" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_rankings_topic_group" ON "public"."topic_mock_rankings"("topic_group_id", "topic_id") WHERE "topic_group_id" IS NOT NULL;
CREATE INDEX "idx_opn_index_date" ON "public"."opn_index" USING "btree" ("date" DESC);
CREATE INDEX "idx_opn_index_users_date" ON "public"."opn_index_users" USING "btree" ("date" DESC);
CREATE INDEX "idx_opn_index_users_user_date" ON "public"."opn_index_users" USING "btree" ("user_id", "date" DESC);
CREATE INDEX "idx_opn_history_user_date" ON "public"."user_opn_index_history" USING "btree" ("user_id", "calculated_at" DESC);
CREATE INDEX "idx_opn_history_index" ON "public"."user_opn_index_history" USING "btree" ("opn_index" DESC);
CREATE INDEX "idx_opn_history_calculated" ON "public"."user_opn_index_history" USING "btree" ("calculated_at" DESC);
CREATE INDEX "idx_opn_history_rank_date" ON "public"."user_opn_index_history" USING "btree" ("calculated_at" DESC, "opn_index" DESC);

-- =====================================================
-- FOREIGN KEYS
-- =====================================================

ALTER TABLE ONLY "public"."specialties" ADD CONSTRAINT "specialties_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."academy_kpis" ADD CONSTRAINT "academy_kpis_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."cms_users" ADD CONSTRAINT "cms_users_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."cms_users" ADD CONSTRAINT "cms_users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id");
ALTER TABLE ONLY "public"."cms_users" ADD CONSTRAINT "cms_users_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialties"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialties"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."membership_levels" ADD CONSTRAINT "membership_levels_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialties"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_memberships" ADD CONSTRAINT "user_memberships_membership_level_id_fkey" FOREIGN KEY ("membership_level_id") REFERENCES "public"."membership_levels"("id");
ALTER TABLE ONLY "public"."user_memberships" ADD CONSTRAINT "user_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."categories" ADD CONSTRAINT "categories_topic_type_fkey" FOREIGN KEY ("topic_type") REFERENCES "public"."topic_type"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."topic_groups" ADD CONSTRAINT "topic_groups_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."topic_groups" ADD CONSTRAINT "topic_groups_topic_type_id_fkey" FOREIGN KEY ("topic_type_id") REFERENCES "public"."topic_type"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id");
ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialties"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_topic_type_id_fkey" FOREIGN KEY ("topic_type_id") REFERENCES "public"."topic_type"("id");
ALTER TABLE ONLY "public"."topic" ADD CONSTRAINT "topic_topic_group_id_fkey" FOREIGN KEY ("topic_group_id") REFERENCES "public"."topic_groups"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."questions" ADD CONSTRAINT "questions_topic_fkey" FOREIGN KEY ("topic") REFERENCES "public"."topic"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."questions" ADD CONSTRAINT "questions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."questions" ADD CONSTRAINT "questions_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id");

ALTER TABLE ONLY "public"."question_options" ADD CONSTRAINT "question_options_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."removed_questions_history" ADD CONSTRAINT "removed_questions_history_removed_by_fkey" FOREIGN KEY ("removed_by") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."user_tests" ADD CONSTRAINT "user_tests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."user_tests" ADD CONSTRAINT "user_tests_topic_group_id_fkey" FOREIGN KEY ("topic_group_id") REFERENCES "public"."topic_groups"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."user_test_answers" ADD CONSTRAINT "user_test_answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id");
ALTER TABLE ONLY "public"."user_test_answers" ADD CONSTRAINT "user_test_answers_selected_option_id_fkey" FOREIGN KEY ("selected_option_id") REFERENCES "public"."question_options"("id");
ALTER TABLE ONLY "public"."user_test_answers" ADD CONSTRAINT "user_test_answers_user_test_id_fkey" FOREIGN KEY ("user_test_id") REFERENCES "public"."user_tests"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "public"."topic"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_tutor_uuid_fkey" FOREIGN KEY ("tutor_uuid") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_editor_id_fkey" FOREIGN KEY ("editor_id") REFERENCES "public"."cms_users"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "public"."academies"("id");
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "public"."specialties"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."challenge" ADD CONSTRAINT "challenge_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_favorite_questions" ADD CONSTRAINT "user_favorite_questions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."user_favorite_questions" ADD CONSTRAINT "user_favorite_questions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."topic_mock_rankings" ADD CONSTRAINT "topic_mock_rankings_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "public"."topic"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."topic_mock_rankings" ADD CONSTRAINT "topic_mock_rankings_topic_group_id_fkey" FOREIGN KEY ("topic_group_id") REFERENCES "public"."topic_groups"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."topic_mock_rankings" ADD CONSTRAINT "topic_mock_rankings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."opn_index_users" ADD CONSTRAINT "opn_index_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_opn_index_history" ADD CONSTRAINT "user_opn_index_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

-- =====================================================
-- FUNCTIONS AND TRIGGERS FOR QUESTION STATISTICS
-- =====================================================

-- Función para actualizar estadísticas de preguntas (num_answered, num_fails, num_empty)
CREATE OR REPLACE FUNCTION "public"."update_question_stats"()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_is_flashcard BOOLEAN;
    v_answered_count INTEGER;
    v_fails_count INTEGER;
    v_empty_count INTEGER;
BEGIN
    -- Obtener si el test es modo flashcard
    SELECT is_flashcard_mode INTO v_is_flashcard
    FROM user_tests
    WHERE id = NEW.user_test_id;

    -- Solo actualizar estadísticas si NO es flashcard
    -- (en modo flashcard las respuestas no se cuentan como aciertos/fallos)
    IF v_is_flashcard THEN
        RETURN NEW;
    END IF;

    -- Calcular estadísticas para esta pregunta
    SELECT
        COUNT(*) FILTER (WHERE correct = true AND selected_option_id IS NOT NULL) as answered,
        COUNT(*) FILTER (WHERE correct = false AND selected_option_id IS NOT NULL) as fails,
        COUNT(*) FILTER (WHERE selected_option_id IS NULL) as empty
    INTO v_answered_count, v_fails_count, v_empty_count
    FROM user_test_answers uta
    INNER JOIN user_tests ut ON uta.user_test_id = ut.id
    WHERE uta.question_id = NEW.question_id
        AND ut.is_flashcard_mode = false;  -- Solo contar tests no-flashcard

    -- Actualizar estadísticas de la pregunta
    UPDATE questions
    SET
        num_answered = v_answered_count,
        num_fails = v_fails_count,
        num_empty = v_empty_count
    WHERE id = NEW.question_id;

    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        RAISE WARNING 'update_question_stats ERROR: %, question_id=%', SQLERRM, NEW.question_id;
        RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."update_question_stats"() OWNER TO "postgres";

COMMENT ON FUNCTION "public"."update_question_stats"() IS
'Actualiza las estadísticas de respuestas de una pregunta (num_answered, num_fails, num_empty) cuando se inserta o actualiza una respuesta. Solo cuenta respuestas de tests no-flashcard.';

-- Trigger para actualizar estadísticas de preguntas
CREATE TRIGGER "trg_update_question_stats"
    AFTER INSERT OR UPDATE ON "public"."user_test_answers"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_question_stats"();

-- Función para recalcular las estadísticas de todas las preguntas
CREATE OR REPLACE FUNCTION "public"."recalculate_all_question_stats"()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- Actualizar estadísticas para todas las preguntas
    UPDATE questions q
    SET
        num_answered = COALESCE(stats.answered, 0),
        num_fails = COALESCE(stats.fails, 0),
        num_empty = COALESCE(stats.empty, 0)
    FROM (
        SELECT
            uta.question_id,
            COUNT(*) FILTER (WHERE uta.correct = true AND uta.selected_option_id IS NOT NULL) as answered,
            COUNT(*) FILTER (WHERE uta.correct = false AND uta.selected_option_id IS NOT NULL) as fails,
            COUNT(*) FILTER (WHERE uta.selected_option_id IS NULL) as empty
        FROM user_test_answers uta
        INNER JOIN user_tests ut ON uta.user_test_id = ut.id
        WHERE ut.is_flashcard_mode = false  -- Solo contar tests no-flashcard
        GROUP BY uta.question_id
    ) stats
    WHERE q.id = stats.question_id;
END;
$$;

ALTER FUNCTION "public"."recalculate_all_question_stats"() OWNER TO "postgres";

COMMENT ON FUNCTION "public"."recalculate_all_question_stats"() IS
'Recalcula las estadísticas de todas las preguntas basándose en las respuestas existentes en user_test_answers (solo tests no-flashcard).';

-- =====================================================
-- END OF MIGRATION
-- =====================================================

