-- =====================================================
-- MIGRATION 5: CRON JOBS AND RLS POLICIES
-- =====================================================
-- Descripción: Cron jobs, RLS policies y configuraciones finales
-- Fecha: 2025-11-05
-- =====================================================

-- =====================================================
-- PARTE 1: OPN INDEX HISTORY TABLE
-- =====================================================
-- Tabla para el historial del índice OPN
-- (Necesaria para la vista creada en Migration 4)

CREATE TABLE IF NOT EXISTS "public"."user_opn_index_history" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,

  -- Total index (0-1000)
  "opn_index" INTEGER NOT NULL,

  -- Breakdown by component
  "quality_trend_score" NUMERIC(6,2) DEFAULT 0,     -- Max: 400
  "recent_activity_score" NUMERIC(6,2) DEFAULT 0,   -- Max: 300
  "competitive_score" NUMERIC(6,2) DEFAULT 0,       -- Max: 200
  "momentum_score" NUMERIC(6,2) DEFAULT 0,          -- Max: 100

  -- Global rank (calculated after all users)
  "global_rank" INTEGER,

  -- Calculation timestamp
  "calculated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Audit
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS "idx_opn_history_user_date"
  ON "public"."user_opn_index_history"("user_id", "calculated_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_opn_history_index"
  ON "public"."user_opn_index_history"("opn_index" DESC);

CREATE INDEX IF NOT EXISTS "idx_opn_history_calculated"
  ON "public"."user_opn_index_history"("calculated_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_opn_history_rank_date"
  ON "public"."user_opn_index_history"("calculated_at" DESC, "opn_index" DESC);

COMMENT ON TABLE "public"."user_opn_index_history" IS
'Stores historical OPN Index calculations for all users. Updated daily via Edge Function.';

COMMENT ON COLUMN "public"."user_opn_index_history"."opn_index" IS
'Total OPN Index score (0-1000 points)';

COMMENT ON COLUMN "public"."user_opn_index_history"."quality_trend_score" IS
'Quality Trend component (0-400 pts): Measures improvement in accuracy over time';

COMMENT ON COLUMN "public"."user_opn_index_history"."recent_activity_score" IS
'Recent Activity component (0-300 pts): Measures practice volume in last 30 days';

COMMENT ON COLUMN "public"."user_opn_index_history"."competitive_score" IS
'Competitiveness component (0-200 pts): Measures positions in Mock rankings';

COMMENT ON COLUMN "public"."user_opn_index_history"."momentum_score" IS
'Momentum component (0-100 pts): Measures acceleration and recent improvement';

COMMENT ON COLUMN "public"."user_opn_index_history"."global_rank" IS
'Global ranking position among all users (1 = best)';

-- =====================================================
-- PARTE 2: ENABLE EXTENSIONS FOR CRON
-- =====================================================

-- Enable pg_cron for scheduled jobs
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Enable pg_net for HTTP requests
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- =====================================================
-- PARTE 3: CRON JOB - OPN INDEX CALCULATION
-- =====================================================

-- Function to trigger OPN Index calculation via Edge Function
CREATE OR REPLACE FUNCTION "public"."trigger_opn_index_calculation"()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  supabase_url text;
  service_role_key text;
  request_id bigint;
BEGIN
  -- Get Supabase URL and Service Role Key from database settings
  -- These should be configured after deployment:
  --   ALTER DATABASE postgres SET app.settings.supabase_url = 'https://your-project-ref.supabase.co';
  --   ALTER DATABASE postgres SET app.settings.supabase_service_key = 'your-service-role-key';

  supabase_url := current_setting('app.settings.supabase_url', true);
  service_role_key := current_setting('app.settings.supabase_service_key', true);

  -- Validate configuration
  IF supabase_url IS NULL THEN
    RAISE NOTICE 'Supabase URL not configured. Please set app.settings.supabase_url';
    RETURN;
  END IF;

  IF service_role_key IS NULL THEN
    RAISE NOTICE 'Service role key not configured. Please set app.settings.supabase_service_key';
    RETURN;
  END IF;

  -- Make HTTP POST request to Edge Function
  SELECT INTO request_id extensions.http_post(
    url := supabase_url || '/functions/v1/calculate-opn-index',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || service_role_key
    ),
    body := jsonb_build_object(
      'recalculate_all', true
    )
  );

  RAISE NOTICE 'OPN Index calculation triggered. Request ID: %', request_id;

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'Error triggering OPN Index calculation: %', SQLERRM;
END;
$$;

COMMENT ON FUNCTION "public"."trigger_opn_index_calculation"() IS
'Triggers the Edge Function to calculate OPN Index for all users. Called by cron job daily.';

GRANT EXECUTE ON FUNCTION "public"."trigger_opn_index_calculation"() TO postgres;

-- Schedule the cron job: Every day at 02:00 UTC
SELECT cron.schedule(
  'calculate-opn-index-daily',
  '0 2 * * *',
  $$SELECT public.trigger_opn_index_calculation();$$
);

-- =====================================================
-- PARTE 4: RLS POLICIES - OPN INDEX HISTORY
-- =====================================================

-- Enable RLS on user_opn_index_history
ALTER TABLE "public"."user_opn_index_history" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view all OPN index data (public rankings)
CREATE POLICY "opn_index_select_all" ON "public"."user_opn_index_history"
  FOR SELECT
  USING (true);

-- Policy: Only service role can insert OPN index data
CREATE POLICY "opn_index_insert_service" ON "public"."user_opn_index_history"
  FOR INSERT
  WITH CHECK (false);  -- Only service role (via edge function) can insert

-- Policy: No updates allowed (immutable history)
CREATE POLICY "opn_index_no_updates" ON "public"."user_opn_index_history"
  FOR UPDATE
  USING (false);

-- Policy: No deletes allowed (preserve history)
CREATE POLICY "opn_index_no_deletes" ON "public"."user_opn_index_history"
  FOR DELETE
  USING (false);

-- =====================================================
-- PARTE 4B: RLS POLICIES - TOPIC MOCK RANKINGS
-- =====================================================

-- Disable RLS on topic_mock_rankings (triggers handle all validation)
ALTER TABLE "public"."topic_mock_rankings" DISABLE ROW LEVEL SECURITY;

-- No RLS policies needed - the trigger update_ranking_on_mock_complete
-- handles all validation and security logic

-- =====================================================
-- PARTE 5: GRANTS AND PERMISSIONS
-- =====================================================

-- Grant permissions for app roles on all tables
GRANT ALL ON TABLE "public"."specialties" TO postgres;
GRANT ALL ON TABLE "public"."specialties" TO anon;
GRANT ALL ON TABLE "public"."specialties" TO authenticated;
GRANT ALL ON TABLE "public"."specialties" TO service_role;

GRANT ALL ON SEQUENCE "public"."specialties_id_seq" TO postgres;
GRANT ALL ON SEQUENCE "public"."specialties_id_seq" TO anon;
GRANT ALL ON SEQUENCE "public"."specialties_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."specialties_id_seq" TO service_role;

-- Add other necessary grants as needed for your app...

-- =====================================================
-- IMPORTANTE: POST-DEPLOYMENT SETUP
-- =====================================================

-- After running this migration, configure these settings:

-- 1. Set your Supabase URL:
--    ALTER DATABASE postgres SET app.settings.supabase_url = 'https://your-project-ref.supabase.co';

-- 2. Set your Service Role Key (keep this secret!):
--    ALTER DATABASE postgres SET app.settings.supabase_service_key = 'your-service-role-key-here';

-- 3. Verify the settings:
--    SELECT current_setting('app.settings.supabase_url', true);
--    SELECT current_setting('app.settings.supabase_service_key', true);

-- 4. Test the function manually (optional):
--    SELECT public.trigger_opn_index_calculation();

-- 5. Check cron job status:
--    SELECT * FROM cron.job WHERE jobname = 'calculate-opn-index-daily';

-- 6. View cron job execution history:
--    SELECT * FROM cron.job_run_details WHERE jobid = (
--      SELECT jobid FROM cron.job WHERE jobname = 'calculate-opn-index-daily'
--    ) ORDER BY start_time DESC LIMIT 10;

-- =====================================================
-- END OF MIGRATION
-- =====================================================