-- =====================================================
-- MIGRATION 6: AI CHAT SYSTEM
-- =====================================================
-- Descripción: Sistema de conversaciones con IA usando RAG
-- Fecha: 2025-11-06
-- =====================================================

-- =====================================================
-- EXTENSIONS
-- =====================================================

-- Extensión para vectores (necesaria para embeddings RAG)
-- Nota: pgvector debe estar instalado en el sistema
-- Para instalarlo localmente: https://github.com/pgvector/pgvector
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "public";
EXCEPTION
    WHEN undefined_file THEN
        RAISE NOTICE 'vector extension not available, RAG features will be limited';
END
$$;

-- =====================================================
-- ENUMS
-- =====================================================

-- Estado de conversación
CREATE TYPE "public"."conversation_status" AS ENUM (
    'active',
    'archived',
    'deleted'
);

ALTER TYPE "public"."conversation_status" OWNER TO "postgres";

-- Rol del mensaje (compatible con OpenAI/DeepSeek)
CREATE TYPE "public"."message_role" AS ENUM (
    'system',
    'user',
    'assistant',
    'function'
);

ALTER TYPE "public"."message_role" OWNER TO "postgres";

-- Proveedor de IA
CREATE TYPE "public"."ai_provider" AS ENUM (
    'openai',
    'deepseek',
    'anthropic',
    'custom'
);

ALTER TYPE "public"."ai_provider" OWNER TO "postgres";

-- =====================================================
-- TABLES
-- =====================================================

-- -----------------------------------------------------
-- 1. SYSTEM_PROMPTS - Prompts fijos del sistema
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."system_prompts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL UNIQUE,
    "slug" varchar(100) NOT NULL UNIQUE,
    "description" text,
    "prompt_text" text NOT NULL,
    "ai_provider" "public"."ai_provider" DEFAULT 'openai' NOT NULL,
    "model" varchar(100) DEFAULT 'gpt-4o-mini' NOT NULL,
    "temperature" decimal(3,2) DEFAULT 0.7,
    "max_tokens" integer DEFAULT 2000,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_default" boolean DEFAULT false NOT NULL,
    "metadata" jsonb DEFAULT '{}'::jsonb,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "updated_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."system_prompts" OWNER TO "postgres";

COMMENT ON TABLE "public"."system_prompts" IS 'Prompts del sistema predefinidos para diferentes casos de uso';
COMMENT ON COLUMN "public"."system_prompts"."slug" IS 'Identificador único para uso en código';
COMMENT ON COLUMN "public"."system_prompts"."temperature" IS 'Creatividad de la respuesta (0-1)';
COMMENT ON COLUMN "public"."system_prompts"."metadata" IS 'Configuración adicional como top_p, frequency_penalty, etc.';

-- -----------------------------------------------------
-- 2. CONVERSATIONS - Conversaciones de usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "system_prompt_id" bigint REFERENCES "public"."system_prompts"("id") ON DELETE SET NULL,
    "title" varchar(255),
    "status" "public"."conversation_status" DEFAULT 'active' NOT NULL,
    "ai_provider" "public"."ai_provider" DEFAULT 'openai' NOT NULL,
    "model" varchar(100) DEFAULT 'gpt-4o-mini' NOT NULL,
    "total_tokens" integer DEFAULT 0,
    "total_cost" decimal(10,6) DEFAULT 0,
    "message_count" integer DEFAULT 0,
    "metadata" jsonb DEFAULT '{}'::jsonb,
    "last_message_at" timestamptz,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "updated_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."conversations" OWNER TO "postgres";

-- Índices para conversations
CREATE INDEX idx_conversations_user_id ON "public"."conversations"("user_id");
CREATE INDEX idx_conversations_status ON "public"."conversations"("status");
CREATE INDEX idx_conversations_created_at ON "public"."conversations"("created_at" DESC);
CREATE INDEX idx_conversations_last_message ON "public"."conversations"("last_message_at" DESC);

COMMENT ON TABLE "public"."conversations" IS 'Conversaciones de usuarios con IA';
COMMENT ON COLUMN "public"."conversations"."title" IS 'Título auto-generado o definido por usuario';
COMMENT ON COLUMN "public"."conversations"."total_tokens" IS 'Total de tokens usados en esta conversación';
COMMENT ON COLUMN "public"."conversations"."total_cost" IS 'Costo total estimado en USD';
COMMENT ON COLUMN "public"."conversations"."metadata" IS 'Configuración específica o contexto adicional';

-- -----------------------------------------------------
-- 3. MESSAGES - Mensajes de conversaciones
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "conversation_id" bigint NOT NULL REFERENCES "public"."conversations"("id") ON DELETE CASCADE,
    "role" "public"."message_role" NOT NULL,
    "content" text NOT NULL,
    "tokens" integer,
    "cost" decimal(10,6),
    "model" varchar(100),
    "finish_reason" varchar(50),
    "function_call" jsonb,
    "metadata" jsonb DEFAULT '{}'::jsonb,
    "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."messages" OWNER TO "postgres";

-- Índices para messages
CREATE INDEX idx_messages_conversation_id ON "public"."messages"("conversation_id");
CREATE INDEX idx_messages_role ON "public"."messages"("role");
CREATE INDEX idx_messages_created_at ON "public"."messages"("created_at" ASC);

COMMENT ON TABLE "public"."messages" IS 'Mensajes individuales dentro de conversaciones';
COMMENT ON COLUMN "public"."messages"."tokens" IS 'Tokens usados en este mensaje';
COMMENT ON COLUMN "public"."messages"."cost" IS 'Costo estimado de este mensaje en USD';
COMMENT ON COLUMN "public"."messages"."finish_reason" IS 'Razón de finalización: stop, length, function_call, etc.';
COMMENT ON COLUMN "public"."messages"."function_call" IS 'Datos de llamada a función si aplica';

-- -----------------------------------------------------
-- 4. CONVERSATION_QUESTIONS - Relación N:M entre conversaciones y preguntas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."conversation_questions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "conversation_id" bigint NOT NULL REFERENCES "public"."conversations"("id") ON DELETE CASCADE,
    "question_id" bigint NOT NULL REFERENCES "public"."questions"("id") ON DELETE CASCADE,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    UNIQUE("conversation_id", "question_id")
);

ALTER TABLE "public"."conversation_questions" OWNER TO "postgres";

-- Índices
CREATE INDEX idx_conversation_questions_conversation ON "public"."conversation_questions"("conversation_id");
CREATE INDEX idx_conversation_questions_question ON "public"."conversation_questions"("question_id");

COMMENT ON TABLE "public"."conversation_questions" IS 'Relación muchos a muchos entre conversaciones y preguntas. Una conversación puede estar asociada a una o más preguntas específicas del test.';


-- =====================================================
-- TRIGGERS
-- =====================================================

-- Trigger para actualizar updated_at en system_prompts
CREATE TRIGGER update_system_prompts_updated_at
    BEFORE UPDATE ON "public"."system_prompts"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_updated_at_column"();

-- Trigger para actualizar updated_at en conversations
CREATE TRIGGER update_conversations_updated_at
    BEFORE UPDATE ON "public"."conversations"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_updated_at_column"();

-- Trigger para actualizar last_message_at y message_count en conversations
CREATE OR REPLACE FUNCTION "public".update_conversation_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE "public"."conversations"
    SET
        last_message_at = NEW.created_at,
        message_count = message_count + 1,
        updated_at = now()
    WHERE id = NEW.conversation_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_conversation_on_new_message
    AFTER INSERT ON "public"."messages"
    FOR EACH ROW
    EXECUTE FUNCTION "public".update_conversation_stats();

-- =====================================================
-- FUNCIONES HELPER
-- =====================================================

-- Función para crear título automático de conversación
CREATE OR REPLACE FUNCTION "public".generate_conversation_title(conversation_big_id bigint)
RETURNS void AS $$
DECLARE
    first_message text;
    generated_title varchar(255);
BEGIN
    -- Obtener el primer mensaje del usuario
    SELECT content INTO first_message
    FROM "public"."messages"
    WHERE conversation_id = conversation_big_id
    AND role = 'user'
    ORDER BY created_at ASC
    LIMIT 1;

    -- Generar título (primeras 50 caracteres)
    IF first_message IS NOT NULL THEN
        generated_title := substring(first_message from 1 for 50);
        IF length(first_message) > 50 THEN
            generated_title := generated_title || '...';
        END IF;

        -- Actualizar conversación
        UPDATE "public"."conversations"
        SET title = generated_title
        WHERE id = conversation_big_id AND title IS NULL;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- RLS (Row Level Security)
-- =====================================================
-- NOTA: RLS deshabilitado por ahora. Se implementará más tarde con políticas
-- adecuadas para el sistema de autenticación personalizado con tokens de WordPress.

-- =====================================================
-- DATOS INICIALES
-- =====================================================

-- Prompts del sistema por defecto
INSERT INTO "public"."system_prompts" ("name", "slug", "description", "prompt_text", "ai_provider", "model", "is_default") VALUES
(
    'Asistente General',
    'general-assistant',
    'Asistente general para preguntas sobre oposiciones',
    'Eres un asistente experto en oposiciones de la Guardia Civil española. Tu objetivo es ayudar a los opositores respondiendo sus preguntas de manera clara, precisa y motivadora. Utiliza un tono profesional pero cercano.',
    'openai',
    'gpt-4o-mini',
    true
),
(
    'Tutor de Estudio',
    'study-tutor',
    'Tutor especializado en técnicas de estudio y memorización',
    'Eres un tutor especializado en técnicas de estudio para oposiciones. Ayudas a los estudiantes a crear planes de estudio, técnicas de memorización y estrategias para optimizar su preparación. Sé motivador y práctico.',
    'openai',
    'gpt-4o-mini',
    false
),
(
    'Experto en Legislación',
    'legal-expert',
    'Experto en legislación y normativa de la Guardia Civil',
    'Eres un experto en la legislación española y la normativa específica de la Guardia Civil. Respondes preguntas sobre leyes, reglamentos y procedimientos con precisión técnica pero comprensible.',
    'openai',
    'gpt-4o-mini',
    false
),
(
    'Corrector de Tests',
    'test-reviewer',
    'Asistente para revisar y explicar respuestas de tests',
    'Eres un corrector especializado en tests de oposiciones. Explicas por qué las respuestas son correctas o incorrectas, proporcionas contexto adicional y ayudas al estudiante a entender los conceptos.',
    'openai',
    'gpt-4o-mini',
    false
);

COMMENT ON TABLE "public"."system_prompts" IS 'Prompts predefinidos para diferentes casos de uso del asistente IA';
